---
- block:
  - name: Getting CentOS vault repo operable
    shell: "{{ item }}"
    args:
      warn: no
    with_items:
      - "sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*"
      - "sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*"

  - name: Installing httpd
    yum:
      name: httpd
      state: present

  - name: Creating user for apache {{ httpd_user }}
    user:
      name: "{{ httpd_user }}"
      shell: /sbin/nologin      

  - name: Creating logs folder
    file:
      path: "{{ httpd_log_path }}"
      state: directory

  - name: Creating www root folder
    file:
      path: "{{ httpd_www_root }}"
      state: directory    

  - name: Setting some default config values from template
    template:
      src: httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
    notify:
      - Restart httpd server 

  - name: Starting httpd service
    service:
      name: httpd
      state: started
      enabled: yes

  - name: Creating index page for httpd testing
    template:
      src: index.html.j2
      dest: "{{ httpd_www_root }}/index.html"

  - name: Enabling firewalld
    service:
      name: firewalld
      state: started
      enabled: yes

  - name: Opening http 80 port for httpd
    firewalld:
      port: "{{ listen_port }}/tcp"
      permanent: yes
      state: enabled
      immediate: yes

  - name: Check that a page returns a status 200 and predefined contents
    uri:
      url: http://{{ ansible_facts.fqdn }}
      return_content: yes
    register: host
    failed_when: "'Role played successfully' not in host.content"

